apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/lizawu68-gmail-com/loopback4-example-todo-list:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/lizawu68-gmail-com/loopback4-example-todo-list:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: loopback4-example-todo-list
        chartPath: charts/loopback4-example-todo-list
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/lizawu68-gmail-com/loopback4-example-todo-list"
          image.tag: "{{.DIGEST_HEX}}"
